name: driver_app
description: Ambulance Driver App with Material 3 Design

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.2.2
  flutter_local_notifications: ^17.2.4
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  google_maps_flutter: ^2.9.0
  url_launcher: ^6.3.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  mysql1: ^0.20.0
  file_picker: ^8.1.2
  flutter_svg: ^2.2.1
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  device_info_plus: ^9.1.2
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/APATKAL_LOGO.jpeg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/APATKAL_LOGO.jpeg
